services:
  postgres:
    image: postgres:16-alpine
    container_name: hotwebinar-pg
    environment:
      POSTGRES_USER: hotwebinar
      POSTGRES_PASSWORD: hotwebinar
      POSTGRES_DB: hotwebinar
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: hotwebinar-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: hotwebinar
      MINIO_ROOT_PASSWORD: hotwebinar-min-12chars
    command: server /data --console-address ":9001"
    volumes:
      - miniodata:/data

volumes:
  pgdata:
  miniodata:
