services:
  postgres:
    image: postgres:16-alpine
    container_name: hotwebinar-pg
    environment:
      POSTGRES_USER: hotwebinar
      POSTGRES_PASSWORD: hotwebinar
      POSTGRES_DB: hotwebinar
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: hotwebinar-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data

  minio:
    image: minio/minio:latest
    container_name: hotwebinar-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: hotwebinar
      MINIO_ROOT_PASSWORD: hotwebinar-min-12chars
    command: server /data --console-address ":9001"
    volumes:
      - miniodata:/data

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    depends_on:
      - postgres
      - redis
      - minio
    environment:
      DATABASE_URL: postgresql://hotwebinar:hotwebinar@postgres:5432/hotwebinar?schema=public
      REDIS_URL: redis://redis:6379
      S3_ENDPOINT: http://minio:9000
      S3_REGION: us-east-1
      S3_ACCESS_KEY: hotwebinar
      S3_SECRET_KEY: hotwebinar-min-12chars
      S3_BUCKET_ORIGINALS: originals-private
      S3_BUCKET_HLS: hls-public
      S3_PUBLIC_BASE_URL: http://localhost:9000
      WORKER_CONCURRENCY: "1"
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
  miniodata:
