import { chromium } from "playwright";
import fs from "node:fs/promises";
import { config } from "../config.js";

async function main() {
  await fs.mkdir(config.recordedDir, { recursive: true });

  const browser = await chromium.launch({ headless: false });
  const ctx = await browser.newContext();
  const page = await ctx.newPage();

  const loginUrl = new URL(config.loginPath, config.baseUrl).toString();
  console.log("Opening", loginUrl);
  await page.goto(loginUrl, { waitUntil: "domcontentloaded" });

  console.log("");
  console.log("=== Manual session ===");
  console.log("1. Log in to the platform");
  console.log("2. Navigate through any flows you want recorded");
  console.log("3. Close the browser window when done");
  console.log("");

  const visitedUrls: string[] = [];
  page.on("framenavigated", (frame) => {
    if (frame === page.mainFrame()) {
      const url = frame.url();
      if (url && url !== "about:blank" && !visitedUrls.includes(url)) {
        visitedUrls.push(url);
      }
    }
  });

  await page.waitForEvent("close", { timeout: 0 }).catch(() => undefined);

  await ctx.storageState({ path: config.authStatePath });
  console.log("Saved auth state →", config.authStatePath);

  const flow = `// Auto-generated by 01-record. Edit freely.
// Replay reads this file as a list of URLs to revisit.
export const visitedUrls: string[] = ${JSON.stringify(visitedUrls, null, 2)};
`;
  await fs.writeFile(config.flowSpecPath, flow);
  console.log("Saved flow →", config.flowSpecPath);
  console.log("Visited URLs:", visitedUrls.length);

  await browser.close();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
