import { chromium, type Response } from "playwright";
import fs from "node:fs/promises";
import path from "node:path";
import { config } from "../config.js";
import { capturedFromResponse, type Captured } from "../lib/network.js";

async function main() {
  await fs.mkdir(config.recordedDir, { recursive: true });

  const harPath = path.join(config.recordedDir, "session.har");
  const browser = await chromium.launch({ headless: false });
  const ctx = await browser.newContext({
    recordHar: { path: harPath, content: "embed" },
  });
  const page = await ctx.newPage();

  const loginUrl = new URL(config.loginPath, config.baseUrl).toString();
  console.log("Opening", loginUrl);
  await page.goto(loginUrl, { waitUntil: "domcontentloaded" });

  console.log("");
  console.log("=== Manual session ===");
  console.log("1. Log in to the platform");
  console.log("2. Navigate through any flows you want recorded");
  console.log("3. Close the browser window (NOT the terminal — Ctrl-C loses data) when done");
  console.log("");

  const visitedUrls: string[] = [];
  page.on("framenavigated", (frame) => {
    if (frame === page.mainFrame()) {
      const url = frame.url();
      if (url && url !== "about:blank" && !visitedUrls.includes(url)) {
        visitedUrls.push(url);
      }
    }
  });

  // Capture every response during the manual session so we can inspect auth flow + APIs.
  const startedAt = Date.now();
  const captured: Captured[] = [];
  const pending: Promise<void>[] = [];
  page.on("response", (resp: Response) => {
    pending.push(
      capturedFromResponse(resp, {
        startedAt,
        now: () => Date.now(),
        bodyMaxChars: config.bodyMaxChars,
      })
        .then((c) => { captured.push(c); })
        .catch(() => undefined),
    );
  });

  await page.waitForEvent("close", { timeout: 0 }).catch(() => undefined);

  await Promise.all(pending);
  await ctx.storageState({ path: config.authStatePath });
  console.log("Saved auth state →", config.authStatePath);

  const networkPath = path.join(config.recordedDir, "session-network.json");
  await fs.writeFile(networkPath, JSON.stringify(captured, null, 2));
  console.log("Saved network →", networkPath, `(${captured.length} requests)`);
  console.log("Saved HAR →", harPath);

  const flow = `// Auto-generated by 01-record. Edit freely.
// Replay reads this file as a list of URLs to revisit.
export const visitedUrls: string[] = ${JSON.stringify(visitedUrls, null, 2)};
`;
  await fs.writeFile(config.flowSpecPath, flow);
  console.log("Saved flow →", config.flowSpecPath);
  console.log("Visited URLs:", visitedUrls.length);
  if (visitedUrls.length === 0) {
    console.warn("Warning: no URLs recorded. Did you navigate after logging in?");
  }

  await browser.close();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
